<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Decline Salary Sheet - {{ $salarySheet->sheet_no }}</title>
    <style>
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            background: #f3f4f6;
            min-height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            padding: 1rem;
        }
        .card {
            background: #fff;
            border-radius: 1rem;
            box-shadow: 0 4px 24px rgba(0,0,0,0.10);
            max-width: 480px;
            width: 100%;
            padding: 2.5rem;
        }
        .icon {
            font-size: 3rem;
            color: #ef4444;
            text-align: center;
            margin-bottom: 1rem;
            line-height: 1;
        }
        h1 {
            font-size: 1.35rem;
            font-weight: 700;
            margin-bottom: 0.4rem;
            color: #111827;
            text-align: center;
        }
        .sheet-badge {
            display: block;
            width: fit-content;
            margin: 0 auto 1.5rem;
            background: #fef2f2;
            color: #991b1b;
            border: 1px solid #fecaca;
            border-radius: 0.5rem;
            padding: 0.4rem 1rem;
            font-weight: 600;
            font-size: 0.9rem;
        }
        .sub-message {
            color: #6b7280;
            font-size: 0.9rem;
            margin-bottom: 1.5rem;
            text-align: center;
            line-height: 1.5;
        }
        label {
            display: block;
            font-size: 0.8rem;
            font-weight: 600;
            color: #374151;
            margin-bottom: 0.5rem;
        }
        textarea {
            width: 100%;
            min-height: 120px;
            padding: 0.75rem;
            border: 1px solid #d1d5db;
            border-radius: 0.5rem;
            font-size: 0.9rem;
            font-family: inherit;
            resize: vertical;
            color: #111827;
        }
        textarea:focus {
            outline: none;
            border-color: #ef4444;
            box-shadow: 0 0 0 3px rgba(239,68,68,0.1);
        }
        .error {
            color: #dc2626;
            font-size: 0.8rem;
            margin-top: 0.4rem;
        }
        .actions {
            display: flex;
            gap: 0.75rem;
            margin-top: 1.5rem;
        }
        .btn {
            flex: 1;
            padding: 0.75rem 1rem;
            border-radius: 0.5rem;
            font-weight: 600;
            font-size: 0.9rem;
            text-align: center;
            text-decoration: none;
            border: none;
            cursor: pointer;
        }
        .btn-decline {
            background: #ef4444;
            color: #fff;
        }
        .btn-decline:hover {
            background: #dc2626;
        }
        .btn-cancel {
            background: #f3f4f6;
            color: #374151;
        }
        .btn-cancel:hover {
            background: #e5e7eb;
        }
        footer {
            margin-top: 1.5rem;
            color: #9ca3af;
            font-size: 0.75rem;
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="card">
        <div class="icon">&#10005;</div>
        <h1>Decline Salary Sheet</h1>
        <div class="sheet-badge">{{ $salarySheet->sheet_no }}</div>

        <p class="sub-message">
            Please tell us why you're declining this salary sheet.
            The officer and admin will be notified with your reason so it can be corrected and resubmitted.
        </p>

        <form method="POST" action="{{ $actionUrl }}">
            @csrf
            <label for="reason">Reason for decline</label>
            <textarea id="reason" name="reason" placeholder="e.g. Attendance amounts don't match the timesheet for June 12–14…" required>{{ old('reason') }}</textarea>
            @error('reason')
                <div class="error">{{ $message }}</div>
            @enderror

            <div class="actions">
                <a href="{{ route('admin.salary-sheets.show', $salarySheet) }}" class="btn btn-cancel">Cancel</a>
                <button type="submit" class="btn btn-decline">Submit Decline</button>
            </div>
        </form>

        <footer>This page was generated by the Salary Management System.</footer>
    </div>
</body>
</html>
